/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package neu.edu.csye6200.userInterface;

import javax.swing.JButton;
import javax.swing.JTextField;

/**
 *
 * @author vivek
 */
public class AddStudentJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AddStudentJPanel
     */
    public AddStudentJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtFieldFName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtFieldLName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtFieldAge = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtFieldFatherName = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtFieldMotherName = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtFieldAddress = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtPhoneNo = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Add Student");
        add(jLabel1);
        jLabel1.setBounds(6, 6, 650, 80);

        jLabel2.setText("FirstName:");
        add(jLabel2);
        jLabel2.setBounds(110, 130, 154, 19);
        add(txtFieldFName);
        txtFieldFName.setBounds(270, 126, 236, 30);

        jLabel3.setText("LastName:");
        add(jLabel3);
        jLabel3.setBounds(110, 170, 154, 14);
        add(txtFieldLName);
        txtFieldLName.setBounds(270, 160, 236, 30);

        jLabel4.setText("Age:");
        add(jLabel4);
        jLabel4.setBounds(110, 210, 154, 16);
        add(txtFieldAge);
        txtFieldAge.setBounds(270, 200, 236, 30);

        jLabel5.setText("Father Name:");
        add(jLabel5);
        jLabel5.setBounds(110, 250, 154, 16);

        txtFieldFatherName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldFatherNameActionPerformed(evt);
            }
        });
        add(txtFieldFatherName);
        txtFieldFatherName.setBounds(270, 240, 236, 30);

        jLabel6.setText("MotherName:");
        add(jLabel6);
        jLabel6.setBounds(110, 290, 154, 16);
        add(txtFieldMotherName);
        txtFieldMotherName.setBounds(270, 280, 236, 30);

        btnAdd.setText("Add Student");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        add(btnAdd);
        btnAdd.setBounds(270, 490, 230, 37);

        jLabel7.setText("Address");
        add(jLabel7);
        jLabel7.setBounds(110, 330, 154, 16);
        add(txtFieldAddress);
        txtFieldAddress.setBounds(270, 320, 236, 30);

        jLabel8.setText("Phone No");
        add(jLabel8);
        jLabel8.setBounds(110, 370, 154, 16);
        add(txtPhoneNo);
        txtPhoneNo.setBounds(270, 360, 236, 30);

        jLabel9.setText("Email");
        add(jLabel9);
        jLabel9.setBounds(110, 410, 154, 16);
        add(txtEmail);
        txtEmail.setBounds(270, 400, 236, 30);

        jLabel10.setText("Password");
        add(jLabel10);
        jLabel10.setBounds(110, 450, 154, 16);
        add(txtPassword);
        txtPassword.setBounds(270, 440, 236, 30);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/studensmall.jpg"))); // NOI18N
        add(jLabel11);
        jLabel11.setBounds(-1510, -250, 2780, 1490);
    }// </editor-fold>//GEN-END:initComponents

    private void txtFieldFatherNameActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtFieldFatherNameActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_txtFieldFatherNameActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_btnAddActionPerformed

    public JTextField getTxtFieldAddress() {
        return txtFieldAddress;
    }

    public void setTxtFieldAddress(JTextField txtFieldAddress) {
        this.txtFieldAddress = txtFieldAddress;
    }

    public JTextField getTxtPhoneNo() {
        return txtPhoneNo;
    }

    public void setTxtPhoneNo(JTextField txtPhoneNo) {
        this.txtPhoneNo = txtPhoneNo;
    }

    public JButton getBtnAdd() {
        return btnAdd;
    }

    public JTextField getTxtEmail() {
        return txtEmail;
    }

    public void setTxtEmail(JTextField txtEmail) {
        this.txtEmail = txtEmail;
    }

    public JTextField getTxtPassword() {
        return txtPassword;
    }

    public void setTxtPassword(JTextField txtPassword) {
        this.txtPassword = txtPassword;
    }

    public void setBtnAdd(JButton btnAdd) {
        this.btnAdd = btnAdd;
    }

    public JTextField getTxtFieldAge() {
        return txtFieldAge;
    }

    public void setTxtFieldAge(JTextField txtFieldAge) {
        this.txtFieldAge = txtFieldAge;
    }

    public JTextField getTxtFieldFName() {
        return txtFieldFName;
    }

    public void setTxtFieldFName(JTextField txtFieldFName) {
        this.txtFieldFName = txtFieldFName;
    }

    public JTextField getTxtFieldFatherName() {
        return txtFieldFatherName;
    }

    public void setTxtFieldFatherName(JTextField txtFieldFatherName) {
        this.txtFieldFatherName = txtFieldFatherName;
    }

    public JTextField getTxtFieldLName() {
        return txtFieldLName;
    }

    public void setTxtFieldLName(JTextField txtFieldLName) {
        this.txtFieldLName = txtFieldLName;
    }

    public JTextField getTxtFieldMotherName() {
        return txtFieldMotherName;
    }

    public void setTxtFieldMotherName(JTextField txtFieldMotherName) {
        this.txtFieldMotherName = txtFieldMotherName;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFieldAddress;
    private javax.swing.JTextField txtFieldAge;
    private javax.swing.JTextField txtFieldFName;
    private javax.swing.JTextField txtFieldFatherName;
    private javax.swing.JTextField txtFieldLName;
    private javax.swing.JTextField txtFieldMotherName;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtPhoneNo;
    // End of variables declaration//GEN-END:variables
}
