/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package neu.edu.csye6200.userInterface;

import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.JToggleButton;

/**
 *
 * @author @karthik
 */
public class ClassRoomJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ClassRoomJPanel
     */
    private JPanel userProcessControlJPanel;

    public ClassRoomJPanel(JPanel userProcessControlJPanel) {
        initComponents();
        this.userProcessControlJPanel = userProcessControlJPanel;
    }

    public JPanel getUserProcessControlJPanel() {
        return userProcessControlJPanel;
    }

    public void setUserProcessControlJPanel(JPanel userProcessControlJPanel) {
        this.userProcessControlJPanel = userProcessControlJPanel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblClassRooms = new javax.swing.JTable();
        btnUploadCSV = new javax.swing.JToggleButton();
        btnshowDetails = new javax.swing.JToggleButton();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Al Bayan", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CLASSROOMS");
        add(jLabel1);
        jLabel1.setBounds(330, 40, 390, 70);

        tblClassRooms.setBackground(new java.awt.Color(153, 153, 153));
        tblClassRooms.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED,
                java.awt.Color.lightGray, new java.awt.Color(102, 102, 102)));
        tblClassRooms.setFont(new java.awt.Font("Hiragino Maru Gothic ProN", 0, 14)); // NOI18N
        tblClassRooms.setForeground(new java.awt.Color(255, 255, 255));
        tblClassRooms.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {

                },
                new String[] {
                        "Age", "Group Size", "Ratio", "Max Groups/Room"
                }) {
            boolean[] canEdit = new boolean[] {
                    false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        tblClassRooms.setToolTipText("");
        tblClassRooms.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        tblClassRooms.setRowHeight(25);
        tblClassRooms.setSelectionBackground(new java.awt.Color(0, 0, 102));
        jScrollPane1.setViewportView(tblClassRooms);

        add(jScrollPane1);
        jScrollPane1.setBounds(110, 140, 820, 340);

        btnUploadCSV.setBackground(new java.awt.Color(255, 255, 255));
        btnUploadCSV.setFont(new java.awt.Font("Al Bayan", 1, 14)); // NOI18N
        btnUploadCSV.setForeground(new java.awt.Color(255, 255, 255));
        btnUploadCSV.setText("Upload Student Roster");
        btnUploadCSV.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        add(btnUploadCSV);
        btnUploadCSV.setBounds(760, 490, 170, 39);

        btnshowDetails.setBackground(new java.awt.Color(255, 255, 255));
        btnshowDetails.setFont(new java.awt.Font("Al Bayan", 1, 14)); // NOI18N
        btnshowDetails.setForeground(new java.awt.Color(255, 255, 255));
        btnshowDetails.setText("Show Details");
        btnshowDetails.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnshowDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnshowDetailsActionPerformed(evt);
            }
        });
        add(btnshowDetails);
        btnshowDetails.setBounds(110, 490, 110, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon(
                getClass().getResource("/resources/aaron-burden-1zR3WNSTnvY-unsplash (1).jpg"))); // NOI18N
        add(jLabel2);
        jLabel2.setBounds(0, 0, 1230, 850);
    }// </editor-fold>//GEN-END:initComponents

    private void btnshowDetailsActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnshowDetailsActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_btnshowDetailsActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JToggleButton btnUploadCSV;
    public javax.swing.JToggleButton btnshowDetails;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblClassRooms;
    // End of variables declaration//GEN-END:variables

    public JTable getTblClassRooms() {
        return tblClassRooms;
    }

    public void setTblClassRooms(JTable tblClassRooms) {
        this.tblClassRooms = tblClassRooms;
    }

    public void setBtnUploadCSV(JToggleButton btnUploadCSV) {
        this.btnUploadCSV = btnUploadCSV;
    }

    public void setBtnshowDetails(JToggleButton btnshowDetails) {
        this.btnshowDetails = btnshowDetails;
    }

    public JToggleButton getBtnUploadCSV() {
        return btnUploadCSV;
    }

    public JToggleButton getBtnshowDetails() {
        return btnshowDetails;
    }

}
