/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package neu.edu.csye6200.userInterface;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import javax.swing.JComboBox;
import javax.swing.JPanel;
import javax.swing.JTable;

/**
 *
 * @author sanjay
 */
public class StateRulesJPanel extends javax.swing.JPanel {
    private JPanel userProcessControllerJPanel;

    /**
     * Creates new form StateRulesJPanel
     */
    public StateRulesJPanel(JPanel userProcessControllerJPanel) {
        initComponents();
        this.userProcessControllerJPanel = userProcessControllerJPanel;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jTable3 = new javax.swing.JTable();
        jTable2 = new javax.swing.JTable();
        jTable4 = new javax.swing.JTable();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Al Bayan", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Massachusetts Immunization Rules");
        add(jLabel1);
        jLabel1.setBounds(140, 20, 680, 60);

        jLabel2.setFont(new java.awt.Font("Al Bayan", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText(
                "Vaccine Name                       Dosage                                 Duration                                   ");
        add(jLabel2);
        jLabel2.setBounds(60, 260, 840, 60);

        jComboBox2.setModel(
                new javax.swing.DefaultComboBoxModel<>(new String[] { "6 - 24", "25 - 48", "49 - 59", "Above 59" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        add(jComboBox2);
        jComboBox2.setBounds(44, 170, 820, 50);

        jTable3.setBackground(new java.awt.Color(153, 153, 153));
        jTable3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTable3.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jTable3.setForeground(new java.awt.Color(255, 255, 255));
        jTable3.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {
                        { "HiB", "1 - 4", "6 Months" },
                        { "DTaP", "4", "6 Months" },
                        { "Polio", "3", "8 Months" },
                },
                new String[] {
                        "Vaccine Name", "Dosage", "Duration"
                }));
        jTable3.setVisible(false);
        add(jTable3);
        jTable3.setBounds(50, 320, 810, 150);

        jTable2.setBackground(new java.awt.Color(153, 153, 153));
        jTable2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTable2.setForeground(new java.awt.Color(255, 255, 255));
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {

                        { "HiB", "2", "3 Months" },
                        { "DTaP", "3", "8 Months" },
                        { "Polio", "2", "4 Months" },
                        { "MMR", "2", "6 Months" }
                },
                new String[] {
                        "Vaccine Name", "Dosage", "Duration"
                }));
        jTable2.setVisible(false);
        add(jTable2);
        jTable2.setBounds(50, 320, 810, 150);

        jTable4.setBackground(new java.awt.Color(153, 153, 153));
        jTable4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTable4.setForeground(new java.awt.Color(255, 255, 255));
        jTable4.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {
                        { "HiB", "1 - 4", "8 Months" },
                        { "DTaP", "4", "6 Months" },
                        { "Polio", "3", "4 Months" },
                        { "MMR", "2", "6 Months" }
                },
                new String[] {
                        "Vaccine Name", "Dosage", "Duration"
                }));
        jTable4.setVisible(false);
        add(jTable4);
        jTable4.setBounds(50, 320, 810, 150);

        jTable1.setBackground(new java.awt.Color(153, 153, 153));
        jTable1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTable1.setForeground(new java.awt.Color(255, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {

                        { "HiB", "2 - 3", "6 Months" },
                        { "DTaP", "1", "6 Months" },
                        { "Hepatities B", "3", "6 Months" },
                        { "MMR", "1", "7 Months" }

                },
                new String[] {
                        "Vaccine Name", "Dosage", "Duration"
                }));
        jTable1.setVisible(true);
        add(jTable1);
        jTable1.setBounds(50, 320, 810, 147);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(
                getClass().getResource("/resources/aaron-burden-1zR3WNSTnvY-unsplash (1).jpg"))); // NOI18N
        jLabel3.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        add(jLabel3);
        jLabel3.setBounds(-20, 0, 1110, 800);

        jLabel4.setFont(new java.awt.Font("Al Bayan", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Massachusetts Immunization Rules");
        add(jLabel4);
        jLabel4.setBounds(140, 20, 680, 60);

        jLabel5.setFont(new java.awt.Font("Al Bayan", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Vaccine Name                       Dosage                                 Duration");
        add(jLabel5);
        jLabel5.setBounds(60, 280, 840, 37);
    }// </editor-fold>//GEN-END:initComponents

    public javax.swing.JComboBox getAge() {
        return this.jComboBox2;
    }

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:

    }// GEN-LAST:event_jComboBox2ActionPerformed

    public JComboBox<String> getjComboBox2() {
        return jComboBox2;
    }

    public void setjComboBox2(JComboBox<String> jComboBox2) {
        this.jComboBox2 = jComboBox2;
    }

    public JTable getjTable1() {
        return jTable1;
    }

    public void setjTable1(JTable jTable1) {
        this.jTable1 = jTable1;
    }

    public JTable getjTable2() {
        return jTable2;
    }

    public void setjTable2(JTable jTable2) {
        this.jTable2 = jTable2;
    }

    public JTable getjTable3() {
        return jTable3;
    }

    public void setjTable3(JTable jTable3) {
        this.jTable3 = jTable3;
    }

    public JTable getjTable4() {
        return jTable4;
    }

    public void setjTable4(JTable jTable4) {
        this.jTable4 = jTable4;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    // End of variables declaration//GEN-END:variables
}
