/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package neu.edu.csye6200.userInterface;

import java.awt.*;
import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.JTable;

/**
 *
 * @author vivek
 */
public class TeacherJPanel extends javax.swing.JPanel {

    /**
     * Creates new form TeacherJPanel
     */
    private JPanel userProcessContainerJPanel;
    private UpdateTeacherJPanel updateTeacherJPanel;
    private AddTeacherJPanel addTeacherJPanel;

    public TeacherJPanel(JPanel userProcessContainerJPanel) {
        initComponents();
        this.userProcessContainerJPanel = userProcessContainerJPanel;
    }

    public void updateTeacherJPanel() {
        updateTeacherJPanel = new UpdateTeacherJPanel();
        userProcessContainerJPanel.add("UpdateTeacherJPanel", updateTeacherJPanel);
        CardLayout layout = (CardLayout) userProcessContainerJPanel.getLayout();
        layout.next(userProcessContainerJPanel);
    }

    public void addTeacherJPanel() {
        addTeacherJPanel = new AddTeacherJPanel();
        userProcessContainerJPanel.add("AddTeacherJPanel", addTeacherJPanel);
        CardLayout layout = (CardLayout) userProcessContainerJPanel.getLayout();
        layout.next(userProcessContainerJPanel);
    }

    public UpdateTeacherJPanel getUpdateTeacherJPanel() {
        return updateTeacherJPanel;
    }

    public void setUpdateTeacherJPanel(UpdateTeacherJPanel udateTeacherJPanel) {
        this.updateTeacherJPanel = udateTeacherJPanel;
    }

    public AddTeacherJPanel getAddTeacherJPanel() {
        return addTeacherJPanel;
    }

    public void setAddTeacherJPanel(AddTeacherJPanel addTeacherJPanel) {
        this.addTeacherJPanel = addTeacherJPanel;
    }

    public JPanel getUserProcessContainerJPanel() {
        return userProcessContainerJPanel;
    }

    public void setUserProcessContainerJPanel(JPanel userProcessContainerJPanel) {
        this.userProcessContainerJPanel = userProcessContainerJPanel;
    }

    public JButton getBtnAddTeacher() {
        return btnAddTeacher;
    }

    public void setBtnAddTeacher(JButton btnAddTeacher) {
        this.btnAddTeacher = btnAddTeacher;
    }

    public JButton getBtnDelete() {
        return btnDelete;
    }

    public void setBtnDelete(JButton btnDelete) {
        this.btnDelete = btnDelete;
    }

    public JButton getBtnUpdateTeacher() {
        return btnUpdateTeacher;
    }

    public void setBtnUpdateTeacher(JButton btnUpdateTeacher) {
        this.btnUpdateTeacher = btnUpdateTeacher;
    }

    public JTable getTblTeacherRecords() {
        return tblTeacherRecords;
    }

    public void setTblTeacherRecords(JTable tblTeacherRecords) {
        this.tblTeacherRecords = tblTeacherRecords;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTeacherRecords = new javax.swing.JTable();
        btnAddTeacher = new javax.swing.JButton();
        btnUpdateTeacher = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        tblTeacherRecords.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tblTeacherRecords.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {

                },
                new String[] {
                        "Teacher ID", "First Name", "Last Name", "Class Assigned"
                }) {
            boolean[] canEdit = new boolean[] {
                    false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblTeacherRecords);

        add(jScrollPane1);
        jScrollPane1.setBounds(140, 110, 750, 300);

        btnAddTeacher.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btnAddTeacher.setText("Add New Teacher");
        btnAddTeacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddTeacherActionPerformed(evt);
            }
        });
        add(btnAddTeacher);
        btnAddTeacher.setBounds(140, 470, 170, 60);

        btnUpdateTeacher.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btnUpdateTeacher.setText("Update Selected Teacher");
        btnUpdateTeacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateTeacherActionPerformed(evt);
            }
        });
        add(btnUpdateTeacher);
        btnUpdateTeacher.setBounds(380, 470, 230, 60);

        btnDelete.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btnDelete.setText("Delete Selected Teacher");
        add(btnDelete);
        btnDelete.setBounds(670, 470, 205, 60);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 102));
        jLabel1.setText("Teacher Details");
        add(jLabel1);
        jLabel1.setBounds(300, 20, 430, 58);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/teacher-back.jpg"))); // NOI18N
        add(jLabel2);
        jLabel2.setBounds(-1450, -40, 2950, 1740);
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateTeacherActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnUpdateTeacherActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_btnUpdateTeacherActionPerformed

    private void btnAddTeacherActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnAddTeacherActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_btnAddTeacherActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddTeacher;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdateTeacher;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblTeacherRecords;
    // End of variables declaration//GEN-END:variables
}
