/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package neu.edu.csye6200.userInterface;

import javax.swing.JButton;
import javax.swing.JRadioButton;
import javax.swing.JTextField;

/**
 *
 * @author karan
 */
public class UpdateImmuizationJPanel extends javax.swing.JPanel {

    /**
     * Creates new form UpdateImmuizationJPanel
     */
    public UpdateImmuizationJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        textFieldName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        textFieldDate = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        radioBtnYes = new javax.swing.JRadioButton();
        raadioBtnNo = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        textFieldDuration = new javax.swing.JTextField();
        btnUpdateImmunization = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        textFieldId = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Update Immunization");
        add(jLabel1);
        jLabel1.setBounds(220, 20, 584, 90);

        jLabel2.setText("Immunization Name");
        add(jLabel2);
        jLabel2.setBounds(340, 140, 180, 24);
        add(textFieldName);
        textFieldName.setBounds(340, 170, 300, 26);

        jLabel3.setText("Immunization Date");
        add(jLabel3);
        jLabel3.setBounds(340, 210, 120, 24);
        add(textFieldDate);
        textFieldDate.setBounds(340, 250, 300, 26);

        jLabel4.setText("Is Immunization Taken");
        add(jLabel4);
        jLabel4.setBounds(340, 310, 144, 16);

        radioBtnYes.setText("Yes");
        radioBtnYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBtnYesActionPerformed(evt);
            }
        });
        add(radioBtnYes);
        radioBtnYes.setBounds(360, 350, 54, 23);

        raadioBtnNo.setText("No");
        raadioBtnNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                raadioBtnNoActionPerformed(evt);
            }
        });
        add(raadioBtnNo);
        raadioBtnNo.setBounds(530, 350, 50, 23);

        jLabel5.setText("Duration");
        add(jLabel5);
        jLabel5.setBounds(340, 410, 111, 16);

        textFieldDuration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldDurationActionPerformed(evt);
            }
        });
        add(textFieldDuration);
        textFieldDuration.setBounds(340, 440, 300, 26);

        btnUpdateImmunization.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnUpdateImmunization.setText("Update Immunization");
        btnUpdateImmunization.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateImmunizationActionPerformed(evt);
            }
        });
        add(btnUpdateImmunization);
        btnUpdateImmunization.setBounds(340, 600, 300, 36);

        jLabel6.setText("Immunization Id");
        add(jLabel6);
        jLabel6.setBounds(340, 500, 111, 14);

        textFieldId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldIdActionPerformed(evt);
            }
        });
        add(textFieldId);
        textFieldId.setBounds(340, 530, 300, 26);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/pexels-anna-shvets-3786215.jpg"))); // NOI18N
        add(jLabel7);
        jLabel7.setBounds(-1190, 0, 2520, 1240);
    }// </editor-fold>//GEN-END:initComponents

    private void radioBtnYesActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_radioBtnYesActionPerformed
        raadioBtnNo.setSelected(false);
    }// GEN-LAST:event_radioBtnYesActionPerformed

    private void raadioBtnNoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_raadioBtnNoActionPerformed
        // TODO add your handling code here:
        radioBtnYes.setSelected(false);
    }// GEN-LAST:event_raadioBtnNoActionPerformed

    private void textFieldDurationActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_textFieldDurationActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_textFieldDurationActionPerformed

    private void btnUpdateImmunizationActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnUpdateImmunizationActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_btnUpdateImmunizationActionPerformed

    private void textFieldIdActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_textFieldIdActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_textFieldIdActionPerformed

    public JButton getBtnUpdateImmunization() {
        return btnUpdateImmunization;
    }

    public JTextField getTextFieldId() {
        return textFieldId;
    }

    public JRadioButton getRaadioBtnNo() {
        return raadioBtnNo;
    }

    public JRadioButton getRadioBtnYes() {
        return radioBtnYes;
    }

    public JTextField getTextFieldDate() {
        return textFieldDate;
    }

    public JTextField getTextFieldDuration() {
        return textFieldDuration;
    }

    public JTextField getTextFieldName() {
        return textFieldName;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnUpdateImmunization;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JRadioButton raadioBtnNo;
    private javax.swing.JRadioButton radioBtnYes;
    private javax.swing.JTextField textFieldDate;
    private javax.swing.JTextField textFieldDuration;
    private javax.swing.JTextField textFieldId;
    private javax.swing.JTextField textFieldName;
    // End of variables declaration//GEN-END:variables
}
