/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package neu.edu.csye6200.userInterface;

import java.awt.CardLayout;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import neu.edu.csye6200.model.Rules;
import neu.edu.csye6200.model.Student;

/**
 *
 * @author @vivek
 */
public class ViewStudentJPanel extends javax.swing.JPanel {
    private JPanel userProcessJPanel;

    public ViewStudentJPanel(JPanel userProcessJPanel) {
        initComponents();
        this.userProcessJPanel = userProcessJPanel;
    }

    public JTable getTblStudents() {
        return tblStudents;
    }

    public void setTblStudents(JTable tblStudents) {
        this.tblStudents = tblStudents;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblStudents = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lblTeacher = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblTeacherRecord = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblStudentRecordForTeacher = new javax.swing.JTable();
        btnStudenAssignedToATeacher = new javax.swing.JButton();
        textFieldStudentsSize = new javax.swing.JTextField();
        textFieldMaxAge = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        textFieldMinAge1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        textFieldTeachersSize = new javax.swing.JTextField();
        textFieldClassRoomName = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        tblStudents.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {

                },
                new String[] {
                        "FirstName", "LastName", "Age", "StudentID"
                }));
        jScrollPane1.setViewportView(tblStudents);

        add(jScrollPane1);
        jScrollPane1.setBounds(26, 110, 560, 180);

        btnBack.setForeground(new java.awt.Color(0, 51, 153));
        btnBack.setText("<Go Back ");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        add(btnBack);
        btnBack.setBounds(32, 7, 130, 40);
        add(jLabel2);
        jLabel2.setBounds(32, 283, 120, 0);

        lblTeacher.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTeacher.setForeground(new java.awt.Color(255, 255, 255));
        lblTeacher.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTeacher.setText("Teacher Details");
        add(lblTeacher);
        lblTeacher.setBounds(-40, 330, 556, 20);

        tblTeacherRecord.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {

                },
                new String[] {
                        "First Name", "Last Name", "Register Time", "Teacher Id"
                }) {
            boolean[] canEdit = new boolean[] {
                    false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblTeacherRecord);

        add(jScrollPane2);
        jScrollPane2.setBounds(20, 350, 440, 300);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 153));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Student Details");
        add(jLabel1);
        jLabel1.setBounds(230, 80, 560, 20);

        tblStudentRecordForTeacher.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {

                },
                new String[] {
                        "Student First Name", "Student Lat Name", "Student Id", "Teacher First Name"
                }));
        jScrollPane3.setViewportView(tblStudentRecordForTeacher);

        add(jScrollPane3);
        jScrollPane3.setBounds(530, 350, 450, 300);

        btnStudenAssignedToATeacher.setForeground(new java.awt.Color(0, 51, 153));
        btnStudenAssignedToATeacher.setText("See assigned students");
        btnStudenAssignedToATeacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStudenAssignedToATeacherActionPerformed(evt);
            }
        });
        add(btnStudenAssignedToATeacher);
        btnStudenAssignedToATeacher.setBounds(14, 680, 970, 40);

        textFieldStudentsSize.setEditable(false);
        add(textFieldStudentsSize);
        textFieldStudentsSize.setBounds(780, 210, 200, 35);

        textFieldMaxAge.setEditable(false);
        add(textFieldMaxAge);
        textFieldMaxAge.setBounds(780, 160, 200, 35);

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 153));
        jLabel3.setText("Min Age");
        add(jLabel3);
        jLabel3.setBounds(600, 120, 76, 16);

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 153));
        jLabel4.setText("MaxAge");
        add(jLabel4);
        jLabel4.setBounds(600, 170, 107, 16);

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 51, 153));
        jLabel5.setText("Capactiy Of Students");
        add(jLabel5);
        jLabel5.setBounds(600, 220, 150, 16);

        textFieldMinAge1.setEditable(false);
        add(textFieldMinAge1);
        textFieldMinAge1.setBounds(780, 110, 200, 35);

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 51, 153));
        jLabel6.setText("Capactiy Of Teachers");
        add(jLabel6);
        jLabel6.setBounds(600, 270, 160, 16);

        textFieldTeachersSize.setEditable(false);
        add(textFieldTeachersSize);
        textFieldTeachersSize.setBounds(780, 260, 200, 35);

        textFieldClassRoomName.setEditable(false);
        textFieldClassRoomName.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        textFieldClassRoomName.setForeground(new java.awt.Color(0, 51, 153));
        textFieldClassRoomName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        add(textFieldClassRoomName);
        textFieldClassRoomName.setBounds(430, 20, 182, 27);

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Assigned students");
        add(jLabel8);
        jLabel8.setBounds(680, 330, 230, 16);
        add(jSeparator1);
        jSeparator1.setBounds(-100, 60, 1130, 10);
        add(jSeparator2);
        jSeparator2.setBounds(-30, 310, 1080, 10);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/tea.jpg"))); // NOI18N
        add(jLabel7);
        jLabel7.setBounds(-150, -70, 1370, 940);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnBackActionPerformed
        userProcessJPanel.remove(this);
        CardLayout layout = (CardLayout) userProcessJPanel.getLayout();
        layout.previous(userProcessJPanel);
    }// GEN-LAST:event_btnBackActionPerformed

    private void btnStudenAssignedToATeacherActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnStudenAssignedToATeacherActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_btnStudenAssignedToATeacherActionPerformed

    public JTable getTblTeacherRecord() {
        return tblTeacherRecord;
    }

    public JPanel getUserProcessJPanel() {
        return userProcessJPanel;
    }

    public void setUserProcessJPanel(JPanel userProcessJPanel) {
        this.userProcessJPanel = userProcessJPanel;
    }

    public JButton getBtnStudenAssignedToATeacher() {
        return btnStudenAssignedToATeacher;
    }

    public JTable getTblStudentRecordForTeacher() {
        return tblStudentRecordForTeacher;
    }

    public JTextField getTextFieldClassRoomName() {
        return textFieldClassRoomName;
    }

    public JTextField getTextFieldMaxAge() {
        return textFieldMaxAge;
    }

    public JTextField getTextFieldMinAge1() {
        return textFieldMinAge1;
    }

    public JTextField getTextFieldStudentsSize() {
        return textFieldStudentsSize;
    }

    public JTextField getTextFieldTeachersSize() {
        return textFieldTeachersSize;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnStudenAssignedToATeacher;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblTeacher;
    private javax.swing.JTable tblStudentRecordForTeacher;
    private javax.swing.JTable tblStudents;
    private javax.swing.JTable tblTeacherRecord;
    private javax.swing.JTextField textFieldClassRoomName;
    private javax.swing.JTextField textFieldMaxAge;
    private javax.swing.JTextField textFieldMinAge1;
    private javax.swing.JTextField textFieldStudentsSize;
    private javax.swing.JTextField textFieldTeachersSize;
    // End of variables declaration//GEN-END:variables
}
